### ISSUE TITLE
cat error for joining twitter data

### ISSUE THREAD

**Issue by shini-tm** [adityathakker/NLP-Corpuses#1]
When I try to run "cat twitter_en_big,txt,gz,part* > twitter_en_big.txt.gz" the file I get cannot be opened by winRAR. "The archive is unknown format or damaged"

**Comment by shini-tm** [comment]
had to resolve to using linux xarchiver, seems to be the only thing that works.

**Comment by adityathakker** [comment]
You have a typo. You have used "," instead of "." as a separator for extensions. 
Try running "cat twitter_en_big.txt.gz.part* > twitter_en_big.txt.gz"
